language: d
d:
  - dmd
services:
  - docker
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t r2zer0/activityd:latest -f Dockerfile .
  - docker push r2zer0/activityd:latest
  - docker build -t r2zer0/activityd-database -f Dockerfile.database .
  - docker push r2zer0/activityd-database
