create type if not exists poststate as enum ('waiting', 'attempting', 'delivered' );

create table if not exists postqueue (
    id integer primary key generated by default as identity,
    state poststate not null default 'waiting',
    obj_id text not null,
    recipient_id text not null
);
