create type if not exists deliverystate as enum ('waiting', 'attempting', 'delivered' );

create table if not exists deliveryqueue (
    id integer primary key generated by default as identity,
    state poststate not null default 'waiting',
    obj_id text not null,
    recipient_id text not null
);

create or replace function delivery_put(obj_id_ text, recipient_id_ text) returns void language sql as $$
    insert into deliveryqueue (obj_id, recipient_id) values (obj_id_, recipient_id_);
$$;

create or replace function delivery_get(out obj_id text, out recipient_id text) language sql as $$
    update deliveryqueue 
    set state = 'attempting'
    where id in (select id from deliveyqueue for update skip locked limit 1)
    returning obj_id, recipient_id;
$$;

